const MAYA_BLUE = "#65C9FF"
const SUMMER_SKY = "#29B4FF"
const WHITE = "#FFFFFF"
const BLACK = "#1C1C1C"
const DARK_GRAY = "#373C46"
const LOGAN = "#9DA6BA"
const BLUE = "#2F80ED"
const BLACK_TRANSPARENT = "#00000030"

export {
  MAYA_BLUE,
  BLUE,
  SUMMER_SKY,
  WHITE,
  BLACK,
  BLACK_TRANSPARENT,
  DARK_GRAY,
  LOGAN,
}
