const MAYA_BLUE = "#65C9FF"
const SUMMER_SKY = "#29B4FF"
const WHITE = "#FFFFFF"
const BLACK = "#1C1C1C"
const DARK_GRAY = "#373C46"
const LOGAN = "#9DA6BA"

export { MAYA_BLUE, SUMMER_SKY, WHITE, BLACK, DARK_GRAY, LOGAN }
